### ISSUE TITLE
Instance Chains termination and decidability

### ISSUE THREAD

**Issue by AntC2** [habit-lang/alb#17]
Hi Habituists, can I ask questions here? I seem to be one of the few people thinking about FunDeps and Instance Overlaps in Haskell. That's a topic on which GHC has pretty much stopped dead since ~2006/introducing Associated Types then Type Families.

Then the last release of Hugs is of the same vintage, and is as 'modern' a platform on which to experiment. I've found Hugs' implementation is far better principled and disciplined. It rejects many of the programs that GHC seems to accept, but for which any attempt to use them gives type errors (as you point out in the Instance Chains paper). 

I've made a limited-scope modification to Hugs that accepts classes with a combo of FunDeps + Overlaps, [subject to narrow rules](https://gitlab.haskell.org/ghc/ghc/issues/15632#note_160109).

I have a question about Instance Chains, and the Predicates on instances. Making the Predicate a condition for an instance applying has some attractions: it's a common newbie mistake to expect instance constraints in Haskell to limit applicability.

But ... are there combinations of instances and Predicates that prevent type inference terminating? Consider

    class C a
    class P a

    instance C Int   if P Bool
        else C Bool  if P Int

    instance P Bool  if C Bool
        else P Int   if C Int

As soon as the compiler accepts any of those instances, then it can accept them all together. But how can it accept any one until it's accepted some other? We seem to be in an infinite regress. Does the `ilab` logic detect this situation? How does it resolve?

Consider 2

    class C2 a
    class P2 a

    instance C2 Int   fails if P2 Bool
        else C2 Int
        else C2 Bool  fails if P2 Int
        else C2 Bool

    instance P2 Bool  fails if C2 Bool
        else P2 Bool
        else P2 Int   fails if C2 Int
        else P2 Int

My Russell's Paradox-detectors are twitching. If we arbitrarily pick `C2 Int` succeeds; then `P2 Int` fails; then `C2 Bool` succeeds; then `P2 Bool` fails; then (hooray!) we didn't introduce a contradiction. But we could equally arbitrarily pick `P2 Bool` succeeds; then flip all the successes/failures; then again no contradiction.

> In `ilab`, we make no effort to ensure completeness or termination, ensuring greater expressiveness as a result. [section 4.2]

Presumably there's some sort of eventual stack-depth limit on instance resolution, as with GHC's `UndecidableInstances`(?)

**Comment by jgbm** [comment]
Luckily, Habit's class system is not based on arbitrarily picking succeeding and failing predicates.

Given the instances you posted, any proof of `P2 Bool` (for instance) must be infinitely deep.  While we make no guarantee that the Habit solver will not attempt to construct such a proof, in this case it does not.
