### ISSUE TITLE
Building via stack errors

### ISSUE THREAD

**Issue by peschkaj** [habit-lang/alb#4]
Building via stack using `make stack && make alb` produces the following error:

```
stack will use a sandboxed GHC it installed
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec
stack exec ghc --  --make -XOverloadedStrings -O2 -j3 -o alb -odir obj -hidir obj -isrc src/Driver.hs -rtsopts

src/Printer/Common.hs:15:8:
    Could not find module ‘Data.Semigroup’
    Use -v to see a list of the files searched for.
make: *** [alb] Error 1
```

Relevant system information:

- stack version: Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
- macOS version: 10.13.6

**Comment by jgbm** [comment]
`Data.Semigroup` has been in the `base` package since GHC 8.0.1.

**Comment by peschkaj** [comment]
The `stack.yaml` references `lts-6.6` which includes `base-compat` 0.9.1. However that package is not new enough to include `Data.Semigroup`. Switching `lts-resolver` to `lts-9.0` allows `alb` to build correctly.

**Comment by peschkaj** [comment]
Fixed in https://github.com/habit-lang/alb/commit/9ff557a212c35288a4f20531f88e3a73b002ce6a
