### ISSUE TITLE
add software license

### ISSUE THREAD

**Issue by pearProgrammr** [habit-lang/alb#6]
Hello,

I think it would be great to have a license on this project so that that terms of use and redistribution of this software are clear. I see that MIL and MIL-tester repositories have a GPL3 license so I thought alb should have some sort of license as well.

Thanks,
Erik

**Comment by fxdpntthm** [comment]
I believe it is BSD3

https://github.com/habit-lang/alb/blob/9ff557a212c35288a4f20531f88e3a73b002ce6a/alb.cabal#L18
